export const CHANGE_IMAGE_INPUT = 'CHANGE_IMAGE_INPUT';
export const SUBMIT_IMAGE = 'SUBMIT_IMAGE';
export const SET_IMAGE_URL ='SET_IMAGE_URL';
export const IMAGE_SUBMIT_SUCCESS = 'IMAGE_SUBMIT_SUCCESS';
export const IMAGE_SUBMIT_FAILED = 'IMAGE_SUBMIT_FAILED';
export const PENDING = 'PENDING';

